# Code stolen from https://stackoverflow.com/a/77002385

name: Check for new release of Fluent
on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Download previous release info
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: fluent-release-info
          workflow_conclusion: success
          workflow: publish.yml
          repo: TakosThings/Fluent-Discord
          if_no_artifact_found: ignore

      - name: Get latest release
        id: get_release
        run: |
          # Fetch release information and extract the release tag
          RELEASE_TAG=$(curl -s https://api.github.com/repos/TakosThings/Fluent-Discord/releases/latest | jq -r '.tag_name')
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest release: $RELEASE_TAG"

      - name: Compare with previous release
        id: compare_release
        run: |
          # Read the release info from the downloaded artifact
          PREVIOUS_RELEASE=$(cat fluent-release-info 2> /dev/null || echo "NONE")
          echo "previous release: $PREVIOUS_RELEASE"

          # Compare the fetched release tag with the previous release tag
          if [ "${{ steps.get_release.outputs.RELEASE_TAG }}" != "$PREVIOUS_RELEASE" ]; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
            echo "Release changed: true"
          else
            echo "release_changed=false" >> $GITHUB_OUTPUT
            echo "Release changed: false"
          fi

      - name: Calls a workflow to download the new Fluent release
        if: steps.compare_release.outputs.release_changed == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
