name: Download the new Fluent version
on:
    workflow_dispatch:

jobs:
    upgrade:
        name: upgrade
        runs-on: ubuntu-latest
        steps:
            # Required for stuff
            - name: Checkout
              uses: actions/checkout@v4
        
            # Downloading the release
            - uses: robinraju/release-downloader@v1.8
              with:
                # The source repository path. Expected format {owner}/{repo}
                repository: TakosThings/Fluent-Discord
                
                # A flag to choose between latest release and remaining releases
                latest: true
                
                # Name of the file to download (use '*' to download all assets other than tarball or zipball)
                fileName: Fluent-Discord-static.theme.css
                
                # Relative path under $GITHUB_WORKSPACE to place the downloaded files
                out-file-path: core/
            
            # Commiting the release to the current repository so it can be used in CSS
            - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
              with:
                author_name: Github Actions
                add: '*'
                fetch: true
                message: "Updated due to a new TakosThings/Fluent-Discord release"
            
                # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
                # Default: true
                push: true
